### ISSUE TITLE
Adicionar scanners de vulnerabilidade

### ISSUE THREAD

**Issue by jpkrohling** [dose-na-nuvem/customers#12]
Existem diversos scanners de vulnerabilidade, incluindo um básico do GitHub mesmo, chamado CodeQL. Este ticket é para implementar o CodeQL. Bônus se implementar também um segundo, como Trivy.

**Comment by claudiobastos** [comment]
lançaram essa semana um outro tbm chamado govulncheck. vou tentar pegar esse issue amanhã
