### ISSUE TITLE
Implementar servidor básico http para o serviço

### ISSUE THREAD

**Issue by jpkrohling** [dose-na-nuvem/customers#18]
Implementar um servidor HTTP com um handler para servir de base para as operações REST.

**Comment by luizgribeiro** [comment]
Já temos algum tipo de entidade mapeada?
Poderia ser interessante já deixar o modelo pronto pra desenvolver os handlers direto.

O que acha?

**Comment by jpkrohling** [comment]
Vou gravar hoje a parte da persistência com banco de dados. Depois vamos colar as partes :-)

**Comment by jpkrohling** [comment]
Fechando, já que a funcionalidade básica está feita. Para os trabalhos futuros, criaremos outras issues.
