### ISSUE TITLE
Adicinar suporte a live reload

### ISSUE THREAD

**Issue by luizgribeiro** [dose-na-nuvem/customers#21]
Não sei o quão é comum utilizar esse tipo de funcionalidade em Go, mas assistindo os vídeos deu pra perceber que o feedback loop fica um pouco truncado por sempre precisar parar e reiniciar a aplicação.

O que acham de adicionar suporte a live reload?
Dando uma pesquisada topei [com esse artigo](https://aprendagolang.com.br/2022/06/30/como-utilizar-live-reload-para-melhorar-sua-produtividade/). Porederíamos utilizar ele como base

**Comment by luizgribeiro** [comment]
Não consigo adicinar labels por aqui.
@jpkrohling, sugiro adicionar `good first issue` e `enhancement` para essa issue (se seguirmos com ela, claro)

**Comment by jpkrohling** [comment]
Eu acho uma ótima ideia adicionar suporte a livereload para desenvolvimento. Pelo que entendi, não precisa mudar nada no nosso código, né?
