### ISSUE TITLE
Remoção de linter Godox

### ISSUE THREAD

**Issue by cassiobotaro** [dose-na-nuvem/customers#28]
No vídeo sobre banco de dados, um dos [erros](https://github.com/dose-na-nuvem/customers/blob/bc3b5de1f47010e07fb47d6e3209dbf81585180d/cmd/start.go#L28) suprimidos em código foi relacioanado ao godox.

Porém se olharmos a lista de linters habilitados atualmente, o mesmo não se encontra. 

Isto acontece porque o [preset](https://github.com/dose-na-nuvem/customers/blob/bc3b5de1f47010e07fb47d6e3209dbf81585180d/.golangci.yaml#L68-L81) configura alguns linters adicionais aos que estão na lista. 

No problema citado o godox é adicionado pelos presets `comment` e `style`.

Uma possível solução é:

```diff
 linters:
   enable-all: false
-  disable-all: true
+  disable-all: false
...
-
+  disable:
+    - godox
```

Outra solução é remoção do bloco de preset e controlar os linters do projetos através da lista `enable`.

@jpkrohling Qual solução acha melhor?

**Comment by jpkrohling** [comment]
Concorco com o @claudiobastos. Melhor deixar tudo explícito.
