### ISSUE TITLE
Revisar documentação de TLS com possibilidade de criação via make

### ISSUE THREAD

**Issue by claudiobastos** [dose-na-nuvem/customers#53]
Atualizar informações de uso do TLS considerando a evolução

- [ ] revisar caminhos apontados na documentação
- [ ] permitir criação dos certificados via make
- [ ] revistar testes de TLS

**Comment by luizgribeiro** [comment]
Agora fiquei na dúvida.

O #57 fechou essa, mas ao que parece a criação dos certs via makefile não foi realizada.
@claudiobastos, acha melhor fechar essa e abrir uma outra ou a gente finaliza nessa issue mesmo?

**Comment by claudiobastos** [comment]
o PR mencionou, mas realmente não fechava a questão, então no meu entender a issue deve permanecer aberta
