### ISSUE TITLE
Configuração a partir de arquivo, flags e variáveis de ambiente

### ISSUE THREAD

**Issue by jpkrohling** [dose-na-nuvem/customers#8]
Atualmente, o projeto ainda não carrega configurações a partir de arquivos ou variáveis de ambiente, apenas flags. O objetivo é utilizar o viper pra carregar das três fontes.

**Comment by jpkrohling** [comment]
@claudiobastos, você está olhando isso, ou posso implementar?

**Comment by claudiobastos** [comment]
sim, estou implementando
